import { tool } from "@opencode-ai/plugin/tool";
import { readState } from "../state";
import { writeFile } from "fs/promises";
import { join } from "path";
import type { FeatureRun, StageId } from "../types";

const STAGE_ORDER: StageId[] = [
  "discover", "scope", "arch", "plan", "skill-fit",
  "env-setup", "scaffold", "implement", "test", "review",
  "refine", "integrate", "deploy", "verify", "finish-report",
];

const STAGE_LABELS: Record<StageId, string> = {
  discover: "Discovery & Requirements",
  scope: "Scope Definition",
  arch: "Architecture Design",
  plan: "Implementation Planning",
  "skill-fit": "Skill Fit Assessment",
  "env-setup": "Environment Setup",
  scaffold: "Scaffolding",
  implement: "Implementation",
  test: "Testing",
  review: "Code Review",
  refine: "Refinement",
  integrate: "Integration",
  deploy: "Deployment",
  verify: "Verification",
  "finish-report": "Finish Report",
};

function formatDuration(start: string, end: string | null): string {
  const s = new Date(start).getTime();
  const e = end ? new Date(end).getTime() : Date.now();
  const diff = e - s;
  if (diff < 60_000) return `${Math.round(diff / 1000)}s`;
  if (diff < 3_600_000) return `${Math.round(diff / 60_000)}m`;
  return `${(diff / 3_600_000).toFixed(1)}h`;
}

function gateIcon(status: string): string {
  if (status === "passed") return "✅";
  if (status === "failed") return "❌";
  if (status === "skipped") return "⏭️";
  return "❓";
}

function stageIcon(status: string): string {
  if (status === "completed") return "✅";
  if (status === "failed") return "❌";
  if (status === "in_progress") return "🔄";
  if (status === "skipped") return "⏭️";
  return "⬜";
}

function generateMarkdownReport(feature: FeatureRun): string {
  const lines: string[] = [];
  const now = new Date().toISOString();

  lines.push(`# Workflow Report: ${feature.feature_id}`);
  lines.push(``);
  lines.push(`**Generated:** ${now}`);
  lines.push(`**Status:** ${feature.status}`);
  lines.push(`**Created:** ${feature.created_at}`);
  if (feature.completed_at) {
    lines.push(`**Completed:** ${feature.completed_at}`);
    lines.push(`**Total Duration:** ${formatDuration(feature.created_at, feature.completed_at)}`);
  }
  lines.push(``);

  // Summary
  const stages = feature.stages || [];
  const completed = stages.filter(s => s.status === "completed").length;
  const failed = stages.filter(s => s.status === "failed").length;
  const skipped = stages.filter(s => s.status === "skipped").length;
  const total = stages.length;
  const progress = total > 0 ? Math.round((completed / total) * 100) : 0;

  lines.push(`## Summary`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Stages | ${total} |`);
  lines.push(`| Completed | ${completed} |`);
  lines.push(`| Failed | ${failed} |`);
  lines.push(`| Skipped | ${skipped} |`);
  lines.push(`| Progress | ${progress}% |`);
  if (feature.approval) {
    lines.push(`| HR Approval | ${feature.approval.outcome} |`);
  }
  lines.push(``);

  // Stage Timeline
  lines.push(`## Stage Timeline`);
  lines.push(``);
  lines.push(`| Stage | Status | Duration | Gates | Artifacts |`);
  lines.push(`|-------|--------|----------|-------|-----------|`);

  for (const stageId of STAGE_ORDER) {
    const exec = stages.find(s => s.stage === stageId);
    if (!exec) continue;
    const label = STAGE_LABELS[stageId] || stageId;
    const icon = stageIcon(exec.status);
    const dur = exec.started_at ? formatDuration(exec.started_at, exec.completed_at) : "-";
    const gatesCount = (exec.gates || []).length;
    const artsCount = (exec.artifacts || []).length;
    lines.push(`| ${icon} ${label} | ${exec.status} | ${dur} | ${gatesCount} | ${artsCount} |`);
  }
  lines.push(``);

  // Gate Details (only failed/skipped)
  const gateIssues = stages.flatMap(s =>
    (s.gates || []).filter(g => g.status === "failed" || g.status === "skipped")
  );
  if (gateIssues.length > 0) {
    lines.push(`## Gate Issues`);
    lines.push(``);
    for (const g of gateIssues) {
      lines.push(`- ${gateIcon(g.status)} **${g.gate_name}** — ${g.status}`);
    }
    lines.push(``);
  }

  // Artifacts
  const allArtifacts = stages.flatMap(s =>
    (s.artifacts || []).map(a => ({ ...a, stage: s.stage }))
  );
  if (allArtifacts.length > 0) {
    lines.push(`## Artifacts`);
    lines.push(``);
    for (const a of allArtifacts) {
      lines.push(`- \`${a.path}\` (${a.artifact_type}) — ${STAGE_LABELS[a.stage as StageId] || a.stage}`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by [MyWorkflow](https://github.com/Launchery/myworkflow)*`);

  return lines.join("\n");
}

function markdownToHtml(md: string, title: string): string {
  // Minimal markdown-to-HTML for report rendering
  let html = md
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/^---$/gm, "<hr>")
    .replace(/\|.*\|/g, (match) => {
      const cells = match.split("|").filter(c => c.trim() !== "");
      if (cells.every(c => c.trim().match(/^-+$/))) return "";
      return "<tr>" + cells.map(c => `<td>${c.trim()}</td>`).join("") + "</tr>";
    });

  // Wrap consecutive <li> in <ul>
  html = html.replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`);
  // Wrap consecutive <tr> in <table>
  html = html.replace(/(<tr>.*<\/tr>\n?)+/g, (match) => `<table>${match}</table>`);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #1f2937; line-height: 1.6; }
  h1 { border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; }
  h2 { margin-top: 2rem; color: #374151; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #e5e7eb; padding: 0.5rem 0.75rem; text-align: left; }
  tr:nth-child(even) { background: #f9fafb; }
  code { background: #f3f4f6; padding: 0.125rem 0.375rem; border-radius: 4px; font-size: 0.875em; }
  hr { border: none; border-top: 1px solid #e5e7eb; margin: 2rem 0; }
  ul { padding-left: 1.5rem; }
</style>
</head>
<body>
${html}
</body>
</html>`;
}

export const wf_report_export = tool({
  description:
    "Export a workflow report for a feature as Markdown or HTML. " +
    "Generates a summary of all stages, gates, artifacts, and timing for a completed or in-progress feature.",
  args: {
    feature_id: tool.schema.string().describe("Feature ID to export report for"),
    format: tool.schema.enum(["markdown", "html"]).default("markdown").describe("Output format: markdown or html"),
    output_path: tool.schema.string().optional().describe("Optional file path to write the report to"),
  },
  async execute(args: { feature_id: string; format?: "markdown" | "html"; output_path?: string }, ctx: { worktree: string }) {
    const state = await readState(ctx.worktree);
    const feature = state.features[args.feature_id];

    if (!feature) {
      return JSON.stringify({
        error: `Feature '${args.feature_id}' not found. Available: ${Object.keys(state.features).join(", ") || "none"}`,
      });
    }

    const format = args.format ?? "markdown";
    const md = generateMarkdownReport(feature);

    if (args.output_path) {
      const content = format === "html" ? markdownToHtml(md, `Report: ${feature.feature_id}`) : md;
      await writeFile(join(ctx.worktree, args.output_path), content, "utf-8");
      return JSON.stringify({
        written: args.output_path,
        format,
        size_bytes: Buffer.byteLength(content),
      });
    }

    return format === "html" ? markdownToHtml(md, `Report: ${feature.feature_id}`) : md;
  },
});
